const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  browseFolder:       ()    => ipcRenderer.invoke('browse-folder'),
  scanFolder:         (p)   => ipcRenderer.invoke('scan-folder', p),
  gsxListProfiles:    (f)   => ipcRenderer.invoke('gsx-list-profiles', f),
  gsxScanBundled:     (o)   => ipcRenderer.invoke('gsx-scan-bundled', o),
  gsxInstallBundled:  (o)   => ipcRenderer.invoke('gsx-install-bundled', o),
  gsxInstallDropped:  (o)   => ipcRenderer.invoke('gsx-install-dropped', o),
  loadConfig:         ()    => ipcRenderer.invoke('load-config'),
  saveConfig:         (c)   => ipcRenderer.invoke('save-config', c),
  siFetchPage:        (o)   => ipcRenderer.invoke('si-fetch-page', o),
  siGetRegistry:      ()    => ipcRenderer.invoke('si-get-registry'),
  siSaveRegistry:     (r)   => ipcRenderer.invoke('si-save-registry', r),
  siGetSnapshot:      ()    => ipcRenderer.invoke('si-get-snapshot'),
  siSaveSnapshot:     (s)   => ipcRenderer.invoke('si-save-snapshot', s),
  siExportSnapshot:       (s)   => ipcRenderer.invoke('si-export-snapshot', s),
  siWriteCommunityRoutes: (s)   => ipcRenderer.invoke('si-write-community-routes', s),
  getWorldMap:            ()    => ipcRenderer.invoke('get-world-map'),
  browseFile:             ()    => ipcRenderer.invoke('browse-file'),
  launchApp:              (o)   => ipcRenderer.invoke('launch-app', o),
  msfsDetect:             ()    => ipcRenderer.invoke('msfs-detect'),
  activateScenery:        (o)   => ipcRenderer.invoke('activate-scenery', o),
  deactivateScenery:      (o)   => ipcRenderer.invoke('deactivate-scenery', o),
  scanPackages:           (o)   => ipcRenderer.invoke('scan-packages', o),
  linkPackages:           (o)   => ipcRenderer.invoke('link-packages', o),
  unlinkPackages:         (o)   => ipcRenderer.invoke('unlink-packages', o),
  pkgDefaultRoots:        ()    => ipcRenderer.invoke('pkg-default-roots'),
  utilAdd:                (o)   => ipcRenderer.invoke('util-add', o),
  fetchDatis:             (o)   => ipcRenderer.invoke('fetch-datis', o),
  launchMsfs:             (o)   => ipcRenderer.invoke('launch-msfs', o),
  openExternal:       (url) => ipcRenderer.send('open-external', url),
  winMinimize:        ()    => ipcRenderer.send('win-minimize'),
  winMaximize:        ()    => ipcRenderer.send('win-maximize'),
  winClose:           ()    => ipcRenderer.send('win-close'),
  rendererLog:        (msg) => ipcRenderer.send('renderer-log', msg),
  getLogPath:         ()    => ipcRenderer.invoke('get-log-path'),
  perfListSessions:   ()    => ipcRenderer.invoke('perf-list-sessions'),
  perfOpenPath:       (p)   => ipcRenderer.invoke('perf-open-path', p),
  perfStartCapture:   ()    => ipcRenderer.invoke('perf-start-capture'),
  perfPrepNext:       ()    => ipcRenderer.invoke('perf-prep-next'),
  perfCaptureStatus:  ()    => ipcRenderer.invoke('perf-capture-status'),
  listRunningApps:    ()    => ipcRenderer.invoke('list-running-apps'),
  flightCloseApps:    (a)   => ipcRenderer.invoke('flight-close-apps', a),
  isPackaged:         () => __dirname.includes('app.asar'),
  onUpdateAvailable:  (cb)  => ipcRenderer.on('update-available',   (_, ver) => cb(ver)),
  onUpdateDownloaded: (cb)  => ipcRenderer.on('update-downloaded',  (_, ver) => cb(ver)),
  installUpdate:      ()    => ipcRenderer.send('install-update'),
  onSiCookieExpired:  (cb)  => ipcRenderer.on('si-cookie-expired',  ()       => cb()),
});
