const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  browseFolder:       ()    => ipcRenderer.invoke('browse-folder'),
  scanFolder:         (p)   => ipcRenderer.invoke('scan-folder', p),
  loadConfig:         ()    => ipcRenderer.invoke('load-config'),
  saveConfig:         (c)   => ipcRenderer.invoke('save-config', c),
  siFetchPage:        (o)   => ipcRenderer.invoke('si-fetch-page', o),
  siGetRegistry:      ()    => ipcRenderer.invoke('si-get-registry'),
  siSaveRegistry:     (r)   => ipcRenderer.invoke('si-save-registry', r),
  siGetSnapshot:      ()    => ipcRenderer.invoke('si-get-snapshot'),
  siSaveSnapshot:     (s)   => ipcRenderer.invoke('si-save-snapshot', s),
  siExportSnapshot:       (s)   => ipcRenderer.invoke('si-export-snapshot', s),
  siWriteCommunityRoutes: (s)   => ipcRenderer.invoke('si-write-community-routes', s),
  getWorldMap:            ()    => ipcRenderer.invoke('get-world-map'),
  browseFile:             ()    => ipcRenderer.invoke('browse-file'),
  launchApp:              (o)   => ipcRenderer.invoke('launch-app', o),
  msfsDetect:             ()    => ipcRenderer.invoke('msfs-detect'),
  activateScenery:        (o)   => ipcRenderer.invoke('activate-scenery', o),
  deactivateScenery:      (o)   => ipcRenderer.invoke('deactivate-scenery', o),
  launchMsfs:             (o)   => ipcRenderer.invoke('launch-msfs', o),
  openExternal:       (url) => ipcRenderer.send('open-external', url),
  winMinimize:        ()    => ipcRenderer.send('win-minimize'),
  winMaximize:        ()    => ipcRenderer.send('win-maximize'),
  winClose:           ()    => ipcRenderer.send('win-close'),
  rendererLog:        (msg) => ipcRenderer.send('renderer-log', msg),
  getLogPath:         ()    => ipcRenderer.invoke('get-log-path'),
  onUpdateAvailable:  (cb)  => ipcRenderer.on('update-available',   (_, ver) => cb(ver)),
  onSiCookieExpired:  (cb)  => ipcRenderer.on('si-cookie-expired',  ()       => cb()),
});
